services:
  - type: web
    name: vynl-proxy
    env: node
    plan: free
    region: ohio
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PYTHON_VERSION
        value: 3.10.12
