services:
  - type: web
    name: vynl-proxy
    env: node
    plan: free
    region: ohio
    buildCommand: |
      npm install
      curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o yt-dlp
      chmod a+rx yt-dlp
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PYTHON_VERSION
        value: 3.10.12
